from __future__ import annotations

TABLE_SCHEMAS: dict[str, list[str]] = {
    "accounts": [
        "id",
        "prop_firm",
        "account_type",
        "account_size",
        "status",
        "purchase_cost",
        "current_pnl",
        "profit_target",
        "drawdown_remaining",
        "notes",
        "created_at",
        "updated_at",
    ],
    "cash_ledger": [
        "id",
        "date",
        "type",
        "prop_firm",
        "account_id",
        "amount",
        "notes",
        "created_at",
    ],
    "journals": [
        "id",
        "date",
        "session",
        "pnl",
        "what_happened",
        "what_worked",
        "what_went_wrong",
        "main_lesson",
        "strategy_tags",
        "setup_tags",
        "screenshot_paths",
        "created_at",
        "updated_at",
    ],
    "trades": [
        "id",
        "trade_key",
        "source",
        "account_id",
        "symbol",
        "side",
        "quantity",
        "entry_time",
        "exit_time",
        "entry_price",
        "exit_price",
        "gross_pnl",
        "fees",
        "net_pnl",
        "strategy",
        "setup",
        "session",
        "notes",
        "imported_at",
    ],
    "daily_performance": [
        "id",
        "date",
        "label",
        "net_pnl",
        "trades_reported",
        "win_rate_percent",
        "max_drawdown",
        "avg_winner",
        "avg_loser",
        "largest_winner",
        "largest_loss",
        "source_file",
        "journal_summary",
        "include_in_daily_total",
        "created_at",
    ],
    "behavior_rules": [
        "id",
        "name",
        "trigger",
        "action",
        "active",
        "rationale",
        "created_at",
        "updated_at",
    ],
}

NUMERIC_COLUMNS: dict[str, list[str]] = {
    "accounts": [
        "account_size",
        "purchase_cost",
        "current_pnl",
        "profit_target",
        "drawdown_remaining",
    ],
    "cash_ledger": ["amount"],
    "journals": ["pnl"],
    "trades": ["quantity", "entry_price", "exit_price", "gross_pnl", "fees", "net_pnl"],
    "daily_performance": [
        "net_pnl",
        "trades_reported",
        "win_rate_percent",
        "max_drawdown",
        "avg_winner",
        "avg_loser",
        "largest_winner",
        "largest_loss",
    ],
}

DATE_COLUMNS: dict[str, list[str]] = {
    "cash_ledger": ["date", "created_at"],
    "accounts": ["created_at", "updated_at"],
    "journals": ["date", "created_at", "updated_at"],
    "trades": ["entry_time", "exit_time", "imported_at"],
    "daily_performance": ["date", "created_at"],
    "behavior_rules": ["created_at", "updated_at"],
}
